export interface Emotion {
  title: string;
  icon: string;
}

export interface EmotionsList {
  rad: Emotion[];
  good: Emotion[];
  meh: Emotion[];
  bad: Emotion[];
  hehe: Emotion[];
  sad: Emotion[];
  goofy: Emotion[];
  excited: Emotion[];
}

export const emotionsList: EmotionsList = {
  rad: [
    { title: "Thrilled", icon: "\u2605" },
    { title: "Ecstatic", icon: "\ud83d\ude0e" },
    { title: "Jubilant", icon: "\ud83c\udf89" },
    { title: "Overjoyed", icon: "\ud83d\ude80" },
    { title: "Delighted", icon: "\ud83c\udf08" },
    { title: "Euphoric", icon: "\ud83d\ude0d" },
    { title: "Blissful", icon: "\ud83d\ude04" },
    { title: "Exhilarated", icon: "\ud83d\ude03" },
    { title: "Elated", icon: "\ud83d\ude00" },
    { title: "Enraptured", icon: "\ud83d\ude0a" },
    { title: "Joyful", icon: "\ud83d\ude18" },
    { title: "Gleeful", icon: "\ud83d\ude01" },
    { title: "Radiant", icon: "\ud83c\udf1f" },
    { title: "Buoyant", icon: "\ud83d\ude42" },
    { title: "Vibrant", icon: "\ud83d\ude43" },
    { title: "Lively", icon: "\ud83d\ude0f" },
    { title: "Upbeat", icon: "\ud83d\ude03" },
    { title: "Triumphant", icon: "\ud83d\udc4c" },
    { title: "Ecstasy", icon: "\ud83d\ude0c" },
    { title: "Exultant", icon: "\ud83d\ude4f" },
  ],
  good: [
    { title: "Happy", icon: "\ud83d\ude03" },
    { title: "Content", icon: "\ud83d\ude0b" },
    { title: "Pleased", icon: "\ud83d\ude0e" },
    { title: "Satisfied", icon: "\ud83d\ude0d" },
    { title: "Cheerful", icon: "\ud83d\ude04" },
    { title: "Optimistic", icon: "\ud83d\ude42" },
    { title: "Grateful", icon: "\ud83d\ude4f" },
    { title: "Fulfilled", icon: "\ud83d\ude18" },
    { title: "Buoyant", icon: "\ud83d\ude42" },
    { title: "Elated", icon: "\ud83d\ude00" },
    { title: "Blessed", icon: "\ud83d\ude4f" },
    { title: "Serene", icon: "\ud83d\ude0c" },
    { title: "Tranquil", icon: "\ud83d\ude0a" },
    { title: "Blissful", icon: "\ud83d\ude0a" },
    { title: "Jovial", icon: "\ud83d\ude04" },
    { title: "Radiant", icon: "\ud83c\udf1f" },
    { title: "Hopeful", icon: "\ud83d\udc4f" },
    { title: "Amiable", icon: "\ud83d\ude42" },
    { title: "Delighted", icon: "\ud83c\udf08" },
    { title: "Elated", icon: "\ud83d\ude00" },
  ],
  meh: [
    { title: "Indifferent", icon: "\ud83d\ude10" },
    { title: "Apathetic", icon: "\ud83e\udd37\u200d" },
    { title: "Uninterested", icon: "\ud83d\ude15" },
    { title: "Lukewarm", icon: "\ud83d\ude10" },
    { title: "Nonchalant", icon: "\ud83d\ude36" },
    { title: "Bored", icon: "\ud83d\ude12" },
    { title: "Tired", icon: "\ud83d\ude2d" },
    { title: "Blase", icon: "\ud83d\ude10" },
    { title: "Disinterested", icon: "\ud83d\ude12" },
    { title: "Detached", icon: "\ud83d\ude10" },
    { title: "Unimpressed", icon: "\ud83d\ude12" },
    { title: "Indifferent", icon: "\ud83d\ude10" },
    { title: "Neutral", icon: "\ud83d\ude10" },
    { title: "Passive", icon: "\ud83d\ude36" },
    { title: "Aloof", icon: "\ud83d\ude10" },
    { title: "Reserved", icon: "\ud83d\ude10" },
    { title: "Stoic", icon: "\ud83d\ude10" },
    { title: "Uninspired", icon: "\ud83d\ude15" },
    { title: "Wearied", icon: "\ud83d\ude2d" },
    { title: "Fatigued", icon: "\ud83d\ude2d" },
  ],
  bad: [
    { title: "Unhappy", icon: "\ud83d\ude1e" },
    { title: "Disappointed", icon: "\ud83d\ude20" },
    { title: "Frustrated", icon: "\ud83d\ude14" },
    { title: "Upset", icon: "\ud83d\ude21" },
    { title: "Angry", icon: "\ud83d\ude22" },
    { title: "Annoyed", icon: "\ud83d\ude21" },
    { title: "Agitated", icon: "\ud83d\ude21" },
    { title: "Irritated", icon: "\ud83d\ude21" },
    { title: "Enraged", icon: "\ud83d\ude20" },
    { title: "Furious", icon: "\ud83d\ude21" },
    { title: "Infuriated", icon: "\ud83d\ude21" },
    { title: "Resentful", icon: "\ud83d\ude14" },
    { title: "Disgruntled", icon: "\ud83d\ude14" },
    { title: "Hostile", icon: "\ud83d\ude21" },
    { title: "Bitter", icon: "\ud83d\ude1e" },
    { title: "Aggravated", icon: "\ud83d\ude21" },
    { title: "Sulky", icon: "\ud83d\ude1e" },
    { title: "Morose", icon: "\ud83d\ude22" },
    { title: "Sullen", icon: "\ud83d\ude1e" },
    { title: "Grumpy", icon: "\ud83d\ude21" },
  ],
  hehe: [
    { title: "Amused", icon: "\ud83d\ude04\ud83d\ude06" },
    { title: "Mirthful", icon: "\ud83d\ude06" },
    { title: "Whimsical", icon: "\ud83e\udd2a" },
    { title: "Silly", icon: "\ud83e\udd2a" },
    { title: "Jocular", icon: "\ud83d\ude1c" },
    { title: "Playful", icon: "\ud83d\ude1c" },
    { title: "Mischievous", icon: "\ud83d\ude1c" },
    { title: "Cheeky", icon: "\ud83d\ude02" },
    { title: "Chuckling", icon: "\ud83d\ude08" },
    { title: "Whimsical", icon: "\ud83e\udd21" },
    { title: "Giggly", icon: "\ud83d\ude04" },
    { title: "Witty", icon: "\ud83d\ude1c" },
    { title: "Humorous", icon: "\ud83e\udd23" },
    { title: "Jocund", icon: "\ud83d\ude1c" },
    { title: "Lighthearted", icon: "\ud83d\ude06" },
    { title: "Facetious", icon: "\ud83d\ude1c" },
    { title: "Amusing", icon: "\ud83d\ude04" },
    { title: "Grinning", icon: "\ud83d\ude04" },
    { title: "Smiling", icon: "\ud83d\ude04" },
    { title: "Frolicsome", icon: "\ud83d\ude1c" },
  ],
  sad: [
    { title: "Melancholic", icon: "\ud83d\ude25" },
    { title: "Sorrowful", icon: "\ud83d\ude22" },
    { title: "Depressed", icon: "\ud83d\ude10" },
    { title: "Grief-stricken", icon: "\ud83d\ude2d" },
    { title: "Heartbroken", icon: "\ud83d\udc94" },
    { title: "Dejected", icon: "\ud83d\ude1e" },
    { title: "Despondent", icon: "\ud83d\ude1e" },
    { title: "Wretched", icon: "\ud83d\ude2d" },
    { title: "Miserable", icon: "\ud83d\ude1e" },
    { title: "Despairing", icon: "\ud83d\ude22" },
    { title: "Sullen", icon: "\ud83d\ude1e" },
    { title: "Dismal", icon: "\ud83d\ude22" },
    { title: "Woeful", icon: "\ud83d\ude25" },
    { title: "Forlorn", icon: "\ud83d\ude25" },
    { title: "Distressed", icon: "\ud83d\ude25" },
    { title: "Downcast", icon: "\ud83d\ude22" },
    { title: "Disheartened", icon: "\ud83d\ude22" },
    { title: "Regretful", icon: "\ud83d\ude22" },
    { title: "Gloomy", icon: "\ud83d\ude22" },
    { title: "Low-spirited", icon: "\ud83d\ude22" },
  ],
  goofy: [
    { title: "Silly", icon: "\ud83e\udd23" },
    { title: "Wacky", icon: "\ud83e\udd23" },
    { title: "Zany", icon: "\ud83e\udd23" },
    { title: "Eccentric", icon: "\ud83e\udd23" },
    { title: "Whimsical", icon: "\ud83e\udd21" },
    { title: "Quirky", icon: "\ud83e\udd23" },
    { title: "Offbeat", icon: "\ud83e\udd23" },
    { title: "Absurd", icon: "\ud83e\udd23" },
    { title: "Outlandish", icon: "\ud83e\udd23" },
    { title: "Foolish", icon: "\ud83e\udd23" },
    { title: "Ridiculous", icon: "\ud83e\udd23" },
    { title: "Crazy", icon: "\ud83e\udd23" },
    { title: "Bizarre", icon: "\ud83e\udd23" },
    { title: "Oddball", icon: "\ud83e\udd23" },
    { title: "Whacky", icon: "\ud83e\udd23" },
    { title: "Surreal", icon: "\ud83e\udd23" },
    { title: "Kooky", icon: "\ud83e\udd23" },
    { title: "Far-out", icon: "\ud83e\udd23" },
    { title: "Madcap", icon: "\ud83e\udd23" },
    { title: "Jocular", icon: "\ud83e\udd23" },
  ],
  excited: [
    { title: "Enthusiastic", icon: "\ud83d\ude03" },
    { title: "Eager", icon: "\ud83c\udf89" },
    { title: "Thrilled", icon: "\ud83e\udd73" },
    { title: "Pumped", icon: "\ud83d\udca8" },
    { title: "Animated", icon: "\ud83d\ude03" },
    { title: "Ecstatic", icon: "\ud83d\ude00" },
    { title: "Exhilarated", icon: "\ud83d\ude02" },
    { title: "Overjoyed", icon: "\ud83d\ude01" },
    { title: "Delighted", icon: "\ud83d\ude06" },
    { title: "Elated", icon: "\ud83d\ude0e" },
    { title: "Rapturous", icon: "\ud83d\ude04" },
    { title: "Jubilant", icon: "\ud83d\ude18" },
    { title: "Fired up", icon: "\ud83d\udcaf" },
    { title: "Euphoric", icon: "\ud83d\ude0d" },
    { title: "Amped", icon: "\ud83d\ude03" },
    { title: "Stoked", icon: "\ud83d\udca8" },
    { title: "Electrified", icon: "\ud83d\ude0c" },
    { title: "Giddy", icon: "\ud83d\ude01" },
    { title: "Ecstatic", icon: "\ud83d\ude01" },
    { title: "Blissful", icon: "\ud83d\ude01" },
  ],
};

export type EmotionCategory = keyof EmotionsList;